version: '3.8'

services:
  deriv-v75-bot:
    build: .
    container_name: deriv-v75-bot
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/deriv_v75
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - deriv-net
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: deriv-mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - deriv-net
    restart: unless-stopped

networks:
  deriv-net:

volumes:
  mongo-data:
