services:
  algo:
    image: node:18-alpine
    container_name: algo
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
      - ./node_modules:/app/node_modules
    networks:
      - algo-net
    restart: unless-stopped
    working_dir: /app/backend
    command: npm run dev

  mongo:
    image: mongo:latest
    container_name: algo-mongo-dev
    volumes:
      - algo-data-dev:/data/db
    networks:
      - algo-net
    restart: unless-stopped

  mongo-debugger:
    image: mongo-express:latest
    container_name: algo-mongo-debugger
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: "false"
    ports:
      - "8081:8081"
    networks:
      - algo-net
    restart: unless-stopped

networks:
  algo-net:

volumes:
  algo-data-dev:
