services:
  deriv-v75-bot:
    build: .
    container_name: deriv-v75-bot-dev
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/deriv_v75_dev
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    networks:
      - deriv-net
    restart: unless-stopped
    command: npm run dev

  mongo:
    image: mongo:latest
    container_name: deriv-mongo-dev
    ports:
      - "27017:27017" # Expose MongoDB port for external access
    volumes:
      - mongo-data-dev:/data/db
    networks:
      - deriv-net
    restart: unless-stopped

networks:
  deriv-net:

volumes:
  mongo-data-dev:
